set -e
true
true
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-core /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K21/configs/config.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-core /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K33/configs/config.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-core /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/configs/config.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/copy_files.py /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/before_rr.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/before_rr.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/assembly_graph_after_simplification.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/assembly_graph_after_simplification.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/final_contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/first_pe_contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/first_pe_contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/strain_graph.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/strain_graph.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/scaffolds.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/scaffolds.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/scaffolds.paths /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/scaffolds.paths /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/assembly_graph_with_scaffolds.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/assembly_graph_with_scaffolds.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/assembly_graph.fastg /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/assembly_graph.fastg /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/K55/final_contigs.paths /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/contigs.paths
true
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/scaffolds.fasta --misc_dir /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/mus_musculus_spades/misc --threshold_for_breaking_scaffolds 3
true
