set -e
true
true
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-hammer /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/corrected/configs/config.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/corrected/corrected.yaml --ext_python_modules_home /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades --max_threads 10 --output_dir /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/corrected --gzip_output
true
true
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-core /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K21/configs/config.info /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K21/configs/mda_mode.info /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K21/configs/careful_mda_mode.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-core /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K33/configs/config.info /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K33/configs/mda_mode.info /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K33/configs/careful_mda_mode.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/spades-core /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/configs/config.info /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/configs/mda_mode.info /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/configs/careful_mda_mode.info
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/copy_files.py /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/before_rr.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/before_rr.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/assembly_graph_after_simplification.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/assembly_graph_after_simplification.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/final_contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/first_pe_contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/first_pe_contigs.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/strain_graph.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/strain_graph.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/scaffolds.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/scaffolds.fasta /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/scaffolds.paths /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/scaffolds.paths /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/assembly_graph_with_scaffolds.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/assembly_graph_with_scaffolds.gfa /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/assembly_graph.fastg /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/assembly_graph.fastg /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/K55/final_contigs.paths /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/contigs.paths
true
true
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/contigs.fasta --assembled /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/misc/assembled_contigs.fasta --assembly_type contigs --output_dir /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades --bin_home /opt/miniconda3/envs/phyluce-1.7.3-x86/bin
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/scaffolds.fasta --assembled /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades --bin_home /opt/miniconda3/envs/phyluce-1.7.3-x86/bin
true
/opt/miniconda3/envs/phyluce-1.7.3-x86/bin/python /opt/miniconda3/envs/phyluce-1.7.3-x86/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/scaffolds.fasta --misc_dir /Users/peytonwells/Desktop/UCE-tutorial/spades-assemblies/alligator_mississippiensis_spades/misc --threshold_for_breaking_scaffolds 3
true
